/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LudoGame } from "./LudoGame";
export * as factories from "./factories";
export { LudoGame__factory } from "./factories/LudoGame__factory";
